# Generated by Django 3.2 on 2022-05-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialperformance',
            name='files',
            field=models.TextField(db_column='files', null=True),
        ),
    ]
