# Generated by Django 3.2 on 2022-05-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SysModel', '0002_alter_materialperformance_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialclassiication',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classid', to='SysModel.materialclassiication'),
        ),
    ]
