# Generated by Django 3.2 on 2025-03-12 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='请输入完整的图书名称', max_length=200, verbose_name='书名')),
                ('author', models.CharField(help_text='格式：姓 名（如：余华）', max_length=100, verbose_name='作者')),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('publish_date', models.DateField(verbose_name='出版日期')),
                ('total_copies', models.PositiveIntegerField(default=1, help_text='该图书的总馆藏数量', verbose_name='总数量')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='可借数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='借阅时间')),
                ('due_date', models.DateTimeField(verbose_name='应还日期')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间')),
                ('status', models.CharField(choices=[('BORROWED', '借阅中'), ('RETURNED', '已归还'), ('OVERDUE', '已逾期')], default='BORROWED', max_length=10, verbose_name='借阅状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_history', to='books.book', verbose_name='借阅图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL, verbose_name='借阅用户')),
            ],
            options={
                'db_table': 'borrowrecord',
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='通知内容')),
                ('notification_type', models.CharField(choices=[('DUE_REMINDER', '到期提醒'), ('SYSTEM', '系统通知')], default='DUE_REMINDER', max_length=20, verbose_name='通知类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.borrowrecord', verbose_name='关联借阅记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP方法')),
                ('params', models.JSONField(default=dict, verbose_name='请求参数')),
                ('duration', models.FloatField(verbose_name='处理时长（秒）')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'db_table': 'apiLog',
            },
        ),
    ]
